name: Compile, test, deploy
on: ["push"]
env:
  GIF_API_KEY: ${{ secrets.giphy_api_key }}
jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: '3.8.5'
      - name: Run test
        run: mvn clean verify
      - name: Generate Jacoco badge
        uses: cicirello/jacoco-badge-generator@v2
      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'commit badge'
          add: '*.svg'